/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

/* NUCLEO-G474RE: user LED LD2 is wired to PA5, user button B1 is
 * wired to PC13. On this board B1 pulls PC13 HIGH when pressed, so
 * an internal pull-down keeps it LOW (released) at rest.
 * No CMSIS/HAL headers are present in this project, so registers
 * are accessed directly by address. */

#define RCC_BASE        (0x40021000UL)
#define RCC_AHB2ENR     (*(volatile uint32_t *)(RCC_BASE + 0x4CUL))

#define GPIOA_BASE      (0x48000000UL)
#define GPIOA_MODER     (*(volatile uint32_t *)(GPIOA_BASE + 0x00UL))
#define GPIOA_ODR       (*(volatile uint32_t *)(GPIOA_BASE + 0x14UL))

#define GPIOC_BASE      (0x48000800UL)
#define GPIOC_MODER     (*(volatile uint32_t *)(GPIOC_BASE + 0x00UL))
#define GPIOC_PUPDR     (*(volatile uint32_t *)(GPIOC_BASE + 0x0CUL))
#define GPIOC_IDR       (*(volatile uint32_t *)(GPIOC_BASE + 0x10UL))

#define GPIOA_EN        (1UL << 0)
#define GPIOC_EN        (1UL << 2)
#define PA5             (5UL)
#define PC13            (13UL)

static void delay(volatile uint32_t count)
{
	while (count--);
}

static uint32_t button_is_pressed(void)
{
	return (GPIOC_IDR & (1UL << PC13)) != 0;
}

int main(void)
{
	uint32_t was_pressed = 0;

	/* Enable GPIOA and GPIOC clocks */
	RCC_AHB2ENR |= GPIOA_EN | GPIOC_EN;

	/* Set PA5 as general purpose output (MODER5 = 01) */
	GPIOA_MODER &= ~(3UL << (PA5 * 2));
	GPIOA_MODER |=  (1UL << (PA5 * 2));

	/* Set PC13 as input (MODER13 = 00) */
	GPIOC_MODER &= ~(3UL << (PC13 * 2));

	/* Pull PC13 down so it reads LOW when the button is released (PUPDR13 = 10) */
	GPIOC_PUPDR &= ~(3UL << (PC13 * 2));
	GPIOC_PUPDR |=  (2UL << (PC13 * 2));

	/* Loop forever */
	for (;;)
	{
		uint32_t pressed_now = button_is_pressed();

		if (pressed_now && !was_pressed)
		{
			/* Rising edge detected: wait out mechanical bounce, then
			 * confirm the button is still down before acting on it. */
			delay(50000UL);

			if (button_is_pressed())
			{
				GPIOA_ODR ^= (1UL << PA5);
			}
		}

		was_pressed = pressed_now;
	}
}
